[package]
name = "interpreter"
version = "0.1.0"
authors = ["Stéphane Campinas <stephane.campinas@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
parser = { path = "../parser" }
failure = "0.1.3"
failure_derive = "0.1.3"
